name: AIzymes

channels: 
  - defaults
  - conda-forge

dependencies:
  - python=3.9 
  - matplotlib 
  - scipy 
  - jupyter 
  - pandas 
  - networkx
  - biopython 
  - accelerate 
  - transformers
  - ambertools
  - pip:
    - pdb-tools
