name: AIzymes

channels: 
  - defaults
  - conda-forge

dependencies:
  - python=3.9 
  - matplotlib 
  - scipy 
  - jupyter 
  - pandas 
  - networkx
  - biopython 
  - accelerate 
  - transformers
  - ambertools
  - umap-learn
  - bio-embeddings-esm
  
  # NOT NEEDED ANYOMRE
  #- pip:
  #  - pdb-tools
